version: "3"
services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "19000:9000"
      - "42330:42330"
    volumes:
      - "./data:/data"
    environment:
      MINIO_ACCESS_KEY: "minioadmin"
      MINIO_SECRET_KEY: "minioadmin"
    command: server /data
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "30m"