version: '3.3'
services:
  master:
    image: crawlabteam/crawlab
    container_name: crawlab_master
    restart: always
    privileged: true
    environment:
      CRAWLAB_NODE_MASTER: "Y"
      CRAWLAB_MONGO_HOST: "mongo"
      CRAWLAB_MONGO_PORT: "27017"
      CRAWLAB_MONGO_DB: "crawlab"
      CRAWLAB_MONGO_USERNAME: "username"
      CRAWLAB_MONGO_PASSWORD: "password"
      CRAWLAB_MONGO_AUTHSOURCE: "admin"
    volumes:
      - "/opt/.crawlab/master:/root/.crawlab"
      - "/opt/crawlab/master:/data"
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  mongo:
    image: mongo:4.2
    restart: always
    privileged: true
    environment:
      MONGO_INITDB_ROOT_USERNAME: "username"
      MONGO_INITDB_ROOT_PASSWORD: "password"
    volumes:
      - "/opt/crawlab/mongo/data/db:/data/db"
    ports:
      - "27017:27017"